"""
Django settings for Bazer project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ
env = environ.Env()
environ.Env.read_env()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mnpb+*uu(9ef7s9@rew=gkf8qcr1m934k8ivn9uobwk&s_@kdk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'core'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Bazer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Bazer.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
AUTH_USER_MODEL = 'core.User'



REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ]
}

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME":timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "AUTH_HEADER_TYPES": ("Bearer",),
}









import os

BKASH_BASE_URL = os.environ.get("BKASH_BASE_URL", "https://sandbox.sandbox.bka.sh/v1.2.0-beta")

BKASH_APP_KEY = os.environ.get("BKASH_APP_KEY", "your_app_key")
BKASH_APP_SECRET = os.environ.get("BKASH_APP_SECRET", "your_app_secret")
BKASH_USERNAME = os.environ.get("BKASH_USERNAME", "your_username")
BKASH_PASSWORD = os.environ.get("BKASH_PASSWORD", "your_password")

# callback URL that bKash will call (set to your public URL in production)
BKASH_CALLBACK_URL = os.environ.get("BKASH_CALLBACK_URL", "http://127.0.0.1:8000/api/payment/bkash/callback/")





STRIPE_PUBLIC_KEY="pk_test_51SlWJ93gtWGimJpJkoRAtV9dJJ7vIczAtUD3fqguy9j15da19cbC9jSyalsRHFjla6HXk6gKJrQSX3fIzCqmhDa500u4tCJ7mK"
STRIPE_SECRET_KEY="sk_test_51SlWJ93gtWGimJpJ2Ww8AlELlDJKbQjOeTZ05gGw55g7W6iWEU7TvueNfCxBpZk1iPToCwl1uW1o7qM7YsR6GvJm00nMYkttx5"
STRIPE_SECRET_WEBHOOK="whsec_bbc2e4efd5228f30494342b4de6e73d4cc15e8d20c9ad67589e280d59e25b3f3"

